project_id = "smatdnlednyhqsypmzzl"

[functions.join-pair]
verify_jwt = true

[functions.love-advisor]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.book-search]
verify_jwt = false

[functions.archive-completed-tasks]
verify_jwt = false

[functions.process-calendar-reminders]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.translate-message]
verify_jwt = true

[functions.newsletter-subscribe]
verify_jwt = false
